<a href="https://colab.research.google.com/github/Sungyubin0129/mini/blob/main/%EB%B9%85%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%88%98%EC%A7%91_%EB%B6%84%EC%84%9D_%EC%8B%9C%EA%B0%81%ED%99%94_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy 모듈을 사용하기 위한 import
import numpy as np
# 10/06

In [16]:
import numpy as np
ls = [1,2,3,4,5]
arr = np.array(ls)
print(arr)
print(type(arr)) #다차원 배열을 표현하는 타입이 ndarray

ls1 = [1,2,3]
ls2 = [4,5,6]
ls3 = ls1+ls2
print(ls3)

arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr3 = arr1+arr2
print(arr3)

ls=[1,2,3]
ls2 = ls*3
print(ls2) #리스트*의 수는 원소를 반복해서 나열함

arr = np.array(ls)
arr2 = arr * 3
print(arr2) #numpy의 ndarray* 정수는 행렬 * 정수 연산을 수행

#%%time을 마킹하면 수행 시간을 측정해줍니다.
#%%time
#arr = np.arange(100000)

#랜덤 함수
arr = np.random.randn(2,3) # 2*3 행렬을 생성 (원소는 랜덤하게 생성)
print(arr)

arr*3

arr.shape # 구조 확인 
arr.ndim # 차원 확인 

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
[5 7 9]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]
[[-0.1440918  -0.37665633 -0.30205561]
 [-0.32790656  0.11237994  1.46929729]]


2

In [20]:
arr.shape # 구조 확인 



(2, 3)

In [21]:
arr.dtype #원소 타입 확인

dtype('float64')

In [22]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [23]:
arr = np.array([1,2,3,4.2])#원소 타입 설정 안해도 자동으로 설정해준다.
print(arr)
print(arr.dtype)
print(type(arr[0]))

[1.  2.  3.  4.2]
float64
<class 'numpy.float64'>


In [24]:
arr = np.array([1,2,3,4.2,'a'])#수와 문자열로 구성 => 모두 문자열로 변환
print(arr)
print(arr.dtype)
print(type(arr[0]))

['1' '2' '3' '4.2' 'a']
<U32
<class 'numpy.str_'>


다차원 배열 생성


In [25]:
#다차원 배열 생성
ls = [[1,2,3],[4,5,6]]
arr = np.array(ls)
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


#소개
https://numpy.org/doc/stable/user/whatisnumpy.html


In [29]:
arr= np.zeros(10)
print("구조",arr.shape)
print("차원",arr.ndim)
print("원소형식",arr.dtype)

구조 (0,)
차원 1
원소형식 float64


In [34]:
arr = np.arange(3,20,6)
print(arr)
print("구조",arr.shape)
print("차원",arr.ndim)
print("원소형식",arr.dtype)

[ 3  9 15]
구조 (3,)
차원 1
원소형식 int64


In [ ]:
arr = np.array([1,2,3])
print(type(arr[0],type(arr[1]),type(arr[2])))
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3.2])
print(type(arr[0],type(arr[1]),type(arr[2])))
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3],dtype = np.int32) # dtype 인자를 이용하여 명시적으로 원소 형식 결정
print(type(arr[0],type(arr[1]),type(arr[2])))
print(arr.dtype)
print(arr)

산술 연산

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("=====")
arr2= arr*arr
print(arr2)

[[1 2 3]
 [4 5 6]]
=====
[[ 1  4  9]
 [16 25 36]]


In [36]:
arr2 = arr**0.5 #0.5** 은 0.5의 거듭제곱인데 루트라고한다.
print(arr2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [37]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,0,2])
filter = arr1>arr2
print(filter)

[False  True  True]


In [47]:
arr1 = np.array([1,2,3])
filter = arr1>=2
print(filter)

[False  True  True]


In [48]:
res = arr[filter]
print(res)

[[4 5 6]
 [7 8 9]]


색인 및 슬라이싱

In [41]:
arr = np.arange(1000)
print(arr[5:8]) #시작값 5 끝값8
print(arr[:8]) #시작값 0 끝값 8
print(arr[995:])#시작값 995 끝값 999

[5 6 7]
[0 1 2 3 4 5 6 7]
[995 996 997 998 999]


In [42]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0],arr[1],arr[2])
print(arr[0][2])
print(arr[0,2])

[1 2 3] [4 5 6] [7 8 9]


In [43]:
#소스 배열을 가지고 간단한 실험을 하기위해서 복사하여 사용하기
cp_arr = arr.copy()
print(cp_arr)
ls1 = cp_arr*2
print(ls1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [46]:
cp_arr = arr.copy()
print(cp_arr)
cp_arr[0][1]=8
print(cp_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]


#구조변경


In [53]:
#arr=[1,2,3] 구조변경 요철할때 하나의 차원은 -1로 ㅍ표현가능
#arr2 = arr.reshape((6,16))
#print("구조",arr2.shape)
#print("차원",arr2.ndim)

AttributeError: ignored

In [54]:
#arr2 = arr.transpose() #arr.T와 arr.transose()는 같은 결과(전치행렬)를 반복한다.
#print(arr)
#print("----")
#print(arr2)

AttributeError: ignored

In [56]:
arr1 = np.random.randn(2,3)
arr2 = np.random.randn(4,5)
arr3 = np.maximum(arr1,arr2)
print(arr3)

ValueError: ignored

#NumPy 안으로


In [ ]:
xs = [x*x+2*x+3 for x in range(10)] #리스트 컴프리헨션
print (xs)


In [59]:
xarr  = np.array([1.1,1,1.2,1.3,1.4])
yarr = np.array([2.1,2.2,2.3,2.4])
cond= np.array({True,False,False,False,False})
result = np.where(cond,xarr,yarr)
print(result)

ValueError: ignored

In [ ]:
ls1 = [1,2,3]
ls2 = ['가','나','다']

for e1,e2 in zip(ls1,ls2):
  print(e1,e2)

In [ ]:
result = [(x if c else y)for x,y,c in zip(xarr,yarr,cond)]
print(result)

In [ ]:
result=[]
for x,y,c in zip(xarr,yarr,cond):
  if c:
    result.append(x)
  else:
    result.append(y)
print(result)

In [65]:
heights = np.random.normal(172,5,100) #평균 172.4 표준편차 5인 표본 1000개 생성
print(heights)

[166.91326992 168.37247549 173.82598649 174.215029   170.66998512
 175.59837724 166.45949181 167.79495105 172.31694279 172.48146376
 178.90116328 168.96649264 165.09530287 165.39425296 171.0234562
 178.62855672 172.43816565 168.63070265 174.11778675 176.73309464
 169.20221759 171.2200284  179.81110373 185.35649475 167.92117344
 176.8192722  165.86643777 179.74448636 172.79527836 168.89039836
 168.99216582 162.9976453  176.04633544 170.49848328 170.72747553
 174.54126947 182.9605354  172.31735696 168.13996094 170.99394735
 170.38941234 173.46398418 182.75363793 176.72117926 173.21237356
 178.39091434 171.5748648  165.91142163 177.58762802 177.21792421
 168.12488187 172.32994579 171.14952371 171.14454628 167.07726131
 172.73777795 171.12549559 173.84744106 178.69615138 171.61666007
 166.11501029 177.41732657 166.79430366 175.93683272 171.60772769
 182.74916981 178.00629326 177.89254076 174.98846724 168.15290861
 165.44401766 177.54266286 168.80027724 172.88835973 171.37812998
 167.480974

In [62]:
print('평균 : ',heights.mean()) 
print('합계 : ',heights.sum())

평균 :  172.10324688593903
합계 :  172103.24688593904


In [74]:
h2 = heights.reshape(20,-1)
print('구조',h2.shape)
print("평균(축1)",h2.mean(axis =1))#로우 별 평균
print("평균(축0)",h2.mean(axis =0))#컬럼 별 평균
print('합계(축0)',h2.sum(axis = 1))#로우 별 평균
print('합계(축1)',h2.sum(axis = 0))#컬럼 별 평균
#분산밀도에 따라 편차의 수가 바뀐다. 
print('분산',h2.var())
print('표준편차',h2.std())
#최댓값 최솟값
print('최솟값이있는 위치',heights.argmin())
print('최댓값이있는 위치',heights.argmax())
print(heights[heights.argmin()])


구조 (20, 5)
평균(축1) [170.7993492  170.93024533 169.87613359 174.10966128 174.70220358
 172.82317461 169.85242108 173.79061403 175.30811745 174.1365506
 169.96523179 173.60470521 171.57424019 176.35787593 171.2106895
 170.37800147 170.29756727 176.08866816 173.8190684  170.18131369]
평균(축0) [173.13034198 171.83840051 172.64200748 172.93926126 171.90144686]
합계(축0) [853.99674602 854.65122664 849.38066795 870.54830641 873.51101791
 864.11587305 849.26210538 868.95307013 876.54058727 870.682753
 849.82615896 868.02352606 857.87120094 881.78937967 856.05344748
 851.89000736 851.48783633 880.44334079 869.095342   850.90656844]
합계(축1) [3462.60683955 3436.76801021 3452.84014965 3458.78522527 3438.02893711]
분산 22.77863820063393
표준편차 4.772697162049352
최솟값이있는 위치 31
최댓값이있는 위치 23
162.99764530223916


In [78]:
arr = np.array([1,2,3,5,7])
print('누적합계 :',arr.cumsum())
print('누적곱:',arr.cumprod())

누적합계 : [ 1  3  6 11 18]
누적곱: [  1   2   6  30 210]


In [79]:
#도수 조사하는 라이브러리 / 이 안에 어떤수가 있는지 체크 하는 것
uni = np.unique(arr)
print(uni)

[1 2 3 5 7]


In [81]:
x= np.array([[1,2,3],[4,5,6]])
y= np.array([[2,3],[5,6],[8,9]])
re = x.dot(y)
print(x)
print(y)
print(re)
#선형 대수 

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[36 42]
 [81 96]]


In [82]:
for _ in range(10):
  print(np.random.uniform(-2,3))
  #uniform -> -2에서 3사이에 랜덤한 실수 반환 

-1.7114738445400506
-0.841920521725259
2.3207155548321685
0.0998349456670784
-0.5385509341460146
2.462505427527569
2.958719860826383
1.3488069495083286
1.5234610431165518
2.850752058969783


In [83]:
for _ in range(20):
    print(np.random.randint(1,5),end = ' ')# 1에서 5사이의 랜덤한 정수 반환
print()
#random uniform, random randint 

4 1 4 3 1 2 2 3 3 2 2 3 2 1 1 3 1 4 1 3 


In [84]:
volan = [1,7,2,8,9]
for _ in range(20):
   print(np.random.choice(volan),end = ' ')
print()


8 1 7 2 8 2 9 2 8 8 1 1 8 1 1 1 9 1 7 8 
